name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Take version
        id: version
        run: echo version=$(grep -Eo '"(v[^"]+)"' include/Globals.h | sed 's/"//g') > $GITHUB_OUTPUT

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run && pio run -t buildfs

      - name: Bundle
        run: python scripts/create_package.py

      - uses: actions/upload-artifact@v4
        with:
          name: 'led-badge.firm'
          path: 'led-badge.firm'

  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: 'led-badge.firm'
          tag_name: ${{ steps.version.outputs.version }}
